# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(db_index=True, help_text='The name of the document in which this bibliography is needed', max_length=50)),
                ('document_url', models.URLField(blank=True, default=None, help_text='The url of the document in which this bibliography is needed', null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='The date of the bibliography', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=60)),
                ('url', models.URLField()),
                ('urldate', models.DateField(blank=True, null=True, verbose_name='url date')),
                ('addendum', models.TextField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('pubstate', models.CharField(blank=True, choices=[('iprep', 'in preparation'), ('sbmit', 'submitted'), ('focom', 'forthcoming'), ('ipres', 'in press'), ('prpub', 'pre-published')], default='', max_length=5)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=2016, null=True, validators=[django.core.validators.MaxValueValidator(2016, message='year is in future')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryBook',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibbutler_web.Entry')),
                ('author', models.CharField(max_length=150)),
                ('editor', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=17)),
                ('titleaddon', models.URLField(blank=True, max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('bibbutler_web.entry',),
        ),
        migrations.CreateModel(
            name='EntryOnline',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibbutler_web.Entry')),
                ('author', models.CharField(blank=True, max_length=150)),
                ('editor', models.CharField(blank=True, max_length=150)),
                ('titleaddon', models.URLField(blank=True, max_length=60, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=60)),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('bibbutler_web.entry', models.Model),
        ),
        migrations.AddField(
            model_name='entry',
            name='bibliography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibbutler_web.Bibliography'),
        ),
        migrations.AddField(
            model_name='entry',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_bibbutler_web.entry_set+', to='contenttypes.ContentType'),
        ),
    ]
