# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('urldate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='url date')),
                ('url', models.URLField(blank=True)),
                ('addendum', models.TextField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('pubstate', models.CharField(blank=True, choices=[('iprep', 'in preparation'), ('sbmit', 'submitted'), ('focom', 'forthcoming'), ('ipres', 'in press'), ('prpub', 'pre-published')], default=None, max_length=5)),
                ('date', models.DateField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(2016, message='year is in future')])),
                ('author', models.CharField(max_length=150)),
                ('editor', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=16)),
                ('titleaddon', models.URLField(blank=True, max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryType_Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('urldate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='url date')),
                ('url', models.URLField()),
                ('addendum', models.TextField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('pubstate', models.CharField(blank=True, choices=[('iprep', 'in preparation'), ('sbmit', 'submitted'), ('focom', 'forthcoming'), ('ipres', 'in press'), ('prpub', 'pre-published')], default=None, max_length=5)),
                ('date', models.DateField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(2016, message='year is in future')])),
                ('author', models.CharField(blank=True, max_length=150)),
                ('editor', models.CharField(blank=True, max_length=150)),
                ('titleaddon', models.URLField(blank=True, max_length=60)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=60)),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
