# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytype_book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrytype_book',
            name='titleaddon',
            field=models.URLField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='entrytype_book',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrytype_book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2016, message='year is in future')]),
        ),
        migrations.AlterField(
            model_name='entrytype_online',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrytype_online',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='entrytype_online',
            name='titleaddon',
            field=models.URLField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='entrytype_online',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2016, message='year is in future')]),
        ),
    ]
