# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0003_bibliography_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='addition',
            field=models.CharField(blank=True, help_text='additional infos like version or something', max_length=10),
        ),
    ]
