# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0004_auto_20160604_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='addendum',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='note',
        ),
    ]
