# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0005_auto_20160615_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='pubstate',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='urldate',
        ),
        migrations.AddField(
            model_name='entrybook',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrybook',
            name='urldate',
            field=models.DateField(blank=True, null=True, verbose_name='url date'),
        ),
        migrations.AddField(
            model_name='entryonline',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='entryonline',
            name='urldate',
            field=models.DateField(blank=True, null=True, verbose_name='url date'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='document_name',
            field=models.CharField(db_index=True, help_text='The name of the document in which this bibliography is needed', max_length=350),
        ),
        migrations.AlterField(
            model_name='entry',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entrybook',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entrybook',
            name='editor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entrybook',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entrybook',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entryonline',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entryonline',
            name='editor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entryonline',
            name='titleaddon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
