# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0006_auto_20160621_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryManual',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibbutler_web.Entry')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('editor', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=60)),
                ('titleaddon', models.CharField(blank=True, max_length=60, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('urldate', models.DateField(blank=True, null=True, verbose_name='url date')),
                ('isbn', models.CharField(blank=True, max_length=17)),
            ],
            options={
                'verbose_name_plural': 'manuals',
                'verbose_name': 'manual',
            },
            bases=('bibbutler_web.entry', models.Model),
        ),
        migrations.CreateModel(
            name='EntryMisc',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibbutler_web.Entry')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('editor', models.CharField(blank=True, max_length=200)),
                ('howpublished', models.CharField(blank=True, max_length=60, null=True)),
                ('titleaddon', models.CharField(blank=True, max_length=60, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('urldate', models.DateField(blank=True, null=True, verbose_name='url date')),
                ('organization', models.CharField(blank=True, max_length=60)),
                ('isbn', models.CharField(blank=True, max_length=17)),
            ],
            options={
                'verbose_name_plural': 'misc entries',
                'verbose_name': 'misc',
            },
            bases=('bibbutler_web.entry', models.Model),
        ),
        migrations.AlterModelOptions(
            name='entrybook',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='entryonline',
            options={'verbose_name': 'online', 'verbose_name_plural': 'online entries'},
        ),
    ]
