# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0007_auto_20160624_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrymisc',
            name='isbn',
        ),
    ]
