# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0008_remove_entrymisc_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryReport',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibbutler_web.Entry')),
                ('author', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reborts',
            },
            bases=('bibbutler_web.entry',),
        ),
        migrations.RemoveField(
            model_name='entrybook',
            name='urldate',
        ),
        migrations.RemoveField(
            model_name='entrymanual',
            name='urldate',
        ),
        migrations.RemoveField(
            model_name='entrymisc',
            name='urldate',
        ),
        migrations.RemoveField(
            model_name='entryonline',
            name='urldate',
        ),
        migrations.AddField(
            model_name='entry',
            name='url_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
