# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibbutler_web', '0009_auto_20160628_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='url_date',
            new_name='urldate',
        ),
    ]
